/// <reference types="@cloudflare/vitest-plugin/types" />

/**
 * Merge the vitest-only `TEST_MIGRATIONS` / `TEST_AUTH_MIGRATIONS` bindings
 * (plain miniflare bindings configured in vitest.config.ts) into the
 * `Cloudflare.Env` interface generated by `wrangler types`
 * (see test/worker-configuration.d.ts — regenerate with `pnpm run test:types:cf`).
 */
declare namespace Cloudflare {
  interface Env {
    TEST_MIGRATIONS: import('@cloudflare/vitest-plugin').D1Migration[]
    TEST_AUTH_MIGRATIONS: import('@cloudflare/vitest-plugin').D1Migration[]
  }
}
